# n=[[1,3],[0],[9,11],[13,15,17]]
# i=0
# max_length=0
# min_length=0
# while i<len(n):
#     a=n[i]
#     c=len(n)
#     if c>max_length:
#         max_length=c
#         e=n[i]
#     elif c<min_length:
#         min_length=c
#         f=n[i]
#     i=i+1
# print("list maximum is","(",max_length,",",e,")")
# print("list minimum is","(",min_length,",",f,")")
        
               
# a=[[1,3],[0],[9,11],[13,15,17]]
# i=0
# max_l=0
# min_l=10
# while i<len(a):
#     n=a[i]
#     c=len(n)
#     if c>max_l:
#         max_l=c
#         e=a[i]
#     elif c<min_l:
#         min_l=c
#         f=a[i]
#     i=i+1
# print("list maximum is","(",max_l,",",e,")")
# print("list minimum is","(",min_l,",",f,")")      
    
    

